baseURL = "https://torchscribe.com/"
languageCode = "en-us"
title = "Against The Tide"
description = "A series of fact-based civilian experience essays documenting U.S. military bombardments"

# Content Management
[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

# Enable for direct rendering of Org files
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    style = "github"
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.org] # This enables direct Org file rendering!
    enableOrgMode = true

# URL Management
[permalinks]
journal = "/journal/:filename/"
projects = "/projects/:filename/"

# Theme Parameters
[params]
  author = "TorchScribe"
  description = "A series of fact-based civilian experience essays documenting U.S. military bombardments"
  mainSections = ["journal"]
  dateFormat = "January 2, 2006"
  copyright = " 2025 Against The Tide · All rights reserved"
  
  # Custom Parameters
  [params.ui]
    darkMode = true
    typewriter = true
    
  [params.footer]
    text = "Curated by TorchScribe"

# Menu Configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Journal"
    url = "/journal/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

# Taxonomy settings
[taxonomies]
  tag = "tags"
  category = "categories"
  year = "years"