#+TITLE: 40 Pyongyang 1950
#+DATE: 1945-01-01
#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: essays
#+HUGO_TAGS: civilian
#+EXPORT_FILE_NAME: 05-49-Tokyo-1945
#+HUGO_CUSTOM_FRONT_MATTER: :location "1945" :year "1945"


Shizuko Nishio was six years old when Tokyo was engulfed in flames during the U.S. firebombing on March 10, 1945. Anticipating her birthday the next day, she was awakened by air raid sirens. Her father led the family to a nearby primary school for shelter, but it was overcrowded. They moved to another school's basement, leaving behind her cousin and a nurse. The next day, they learned that the initial shelter had become a death trap, with over 200 people perishing inside. Nishio was the sole survivor among her kindergarten classmates.

The bombing destroyed 41 square kilometers of Tokyo, killed an estimated 100,000 civilians, and left a million homeless. Despite the scale of devastation, survivors like Nishio have struggled for recognition and compensation.

**Source:** [The Guardian](https://www.theguardian.com/world/2025/mar/10/great-tokyo-air-raid-firebombing-anniversary-america-survivors)

* Sources
:PROPERTIES:
:EXPORT_EXCLUDE: t
:END:
