#+TITLE: Dresden 1945
#+DATE: 1945-01-01
#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: essays
#+HUGO_TAGS: Civilians
#+EXPORT_FILE_NAME: 02-13-Dresden-1945.org
#+LOCATION: Germany
#+YEAR: 1945
#+HUGO_CATEGORIES: World War II

Lothar Metzger was nine years old when the Allied bombing of Dresden began. On the first night, he and his mother fled to a basement shelter as the city was engulfed in flames. They survived the first wave, but when they emerged, they found much of their neighborhood obliterated. The following day, they watched as new waves of bombers returned.

The resulting firestorm melted asphalt, suffocated thousands, and consumed entire districts. Metzger and his mother walked for days through the ruins, witnessing piles of bodies laid out in courtyards. His testimony later appeared in multiple postwar documentaries.

The bombing campaign by British and American forces resulted in the deaths of approximately 25,000 people and the near-total destruction of one of Germany's most culturally rich cities.

**Source:** [[https://www.bbc.com/news/world-europe-51475494][BBC]]
